[theme]
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F8"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true  # Changed to true
enableXsrfProtection = true  # Keep this true